---
apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Time to celebrate!</title>
    <style>
    html { color-scheme:light dark; }
    body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; background-color: cyan; }
    </style>
    </head>
    <body>
    <h1>Time to celebrate!</h1>
    <h2>You have successfully completed Helm Module!!!!</h2>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-helm-module
  labels:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
