---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helm-module
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
