{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-helm-module
  labels:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
{{- end }}

